CFLAGS=-g


all: q1 q2 q3 q4 q5 q6 q7 q8

clean:
	rm -f q1.out q2.out q3.out q4.out q5.out q6.out q7.out q8.out

q1: q1.c
	gcc -o q1.out q1.c $(CFLAGS) 

q2: q2.c
	gcc -o q2.out q2.c $(CFLAGS)

q3: q3.c
	gcc -o q3.out q3.c $(CFLAGS)

q4: q4.c
	gcc -o q4.out q4.c $(CFLAGS)

q5: q5.c
	gcc -o q5.out q5.c $(CFLAGS)

q6: q6.c
	gcc -o q6.out q6.c $(CFLAGS)

q7: q7.c
	gcc -o q7.out q7.c $(CFLAGS)

q8: q8.c
	gcc -o q8.out q8.c $(CFLAGS)
